#ifndef _DOC7_H_
#define _DOC7_H_

#include "WPILib.h"
#include "CustomDrive.h" 

#define NUM_JAGS 4
#define DOC7_GYRO_PORT 1

#define DOC7_RELAY_PORT 1
#define DOC7_COMPRESSOR_PORT 1

#define DOC7_SOL_MODULE 3
#define DOC7_SOL_OPEN 2
#define DOC7_SOL_CLOSE 1

#define DOC7_STICK_DRIVE 1
#define DOC7_STICK_MANIPULATOR 2

#define DOC7_SHOULDER_A_CHANNEL 2	//nonex Enc
#define DOC7_SHOULDER_B_CHANNEL 3	//
#define DOC7_SHOULDER_PWM_PORT 5//

#define DOC7_MAN_A_CHANNEL 4
#define DOC7_MAN_B_CHANNEL 5
#define DOC7_MAN_PWM_PORT 6

#define DOC7_DOUBLE_SOL_A_PORT 3
#define DOC7_DOUBLE_SOL_B_PORT 4

#define DOC7_LIMIT_SWITCH_PORT 14

#define DOC7_LEFT_LINE_PORT 6
#define DOC7_CENTER_LINE_PORT 7
#define DOC7_RIGHT_LINE_PORT 8

#define DOC7_RED_WHITE_SPIKE 2
#define DOC7_BLUE_SPIKE 3



#endif
